
# Assignment 2 for Course 1MS041
Make sure you pass the `# ... Test` cells and
 submit your solution notebook in the corresponding assignment on the course website. You can submit multiple times before the deadline and your highest score will be used.

---
## Assignment 2, PROBLEM 1
Maximum Points = 8


A courier company operates a fleet of delivery trucks that make deliveries to different parts of the city. The trucks are equipped with GPS tracking devices that record the location of each truck at regular intervals. The locations are divided into three regions: downtown, the suburbs, and the countryside. The following table shows the probabilities of a truck transitioning between these regions at each time step:

| Current region | Probability of transitioning to downtown | Probability of transitioning to the suburbs | Probability of transitioning to the countryside |
|----------------|--------------------------------------------|-----------------------------------------------|------------------------------------------------|
| Downtown       | 0.3                                      | 0.4                                           | 0.3                                            |
| Suburbs        | 0.2                                      | 0.5                                           | 0.3                                            |
| Countryside    | 0.4                                      | 0.3                                           | 0.3                                            |

1. If a truck is currently in the suburbs, what is the probability that it will be in the downtown region after two time steps? [1.5p]
2. If a truck is currently in the suburbs, what is the probability that it will be in the downtown region **the first time** after two time steps? [1.5p]
3. Is this Markov chain irreducible? [1.5p]
4. What is the stationary distribution? [1.5p]
5. Advanced question: What is the expected number of steps until the first time one enters the downtown region having started in the suburbs region. Hint: to get within 1 decimal point, it is enough to compute the probabilities for hitting times below 30. [2p]



-----

1. If a truck is currently in the suburbs, what is the probability that it will be in the downtown region after two time steps? [1.5p]


## 1. [1.5p]

We define the transition matrix

$$
P =
\begin{pmatrix}
0.3 & 0.4 & 0.3 \\
0.2 & 0.5 & 0.3 \\
0.4 & 0.3 & 0.3
\end{pmatrix}
$$

The probability of being in the downtown region after two steps, starting in the suburbs, is the entry in row 2 and column 1 of the squared matrix:

$$
P^2 = P \cdot P
$$

The entry is computed as

$$
(P^2)_{2,1}
= P_{2,1} P_{1,1}
+ P_{2,2} P_{2,1}
+ P_{2,3} P_{3,1}
$$

$$
= 0.2 \cdot 0.3
+ 0.5 \cdot 0.2
+ 0.3 \cdot 0.4
$$

$$
= 0.06 + 0.10 + 0.12 = 0.28
$$

Thus, the probability that the truck is in the downtown region after two time steps is

$$
0.28
$$


Or simply. Just multiply the matrixes and look ath the $P^2$ matrix from suburbs to downtown, and that's the correct value. 

In [2]:
# Part 1

# Fill in the answer to part 1 below as a decimal number
import numpy as np

P = np.array([
    [0.3, 0.4, 0.3],  # Downtown
    [0.2, 0.5, 0.3],  # Suburbs
    [0.4, 0.3, 0.3]   # Countryside
])

print("Matrix P: \n", P)

# Compute P squared
P2 = np.matmul(P, P)

# Extract the probability of Suburbs -> Downtown in 2 steps
value = P2[1][0]

problem1_p1 = value
print("Value for exercise is: ", problem1_p1)


Matrix P: 
 [[0.3 0.4 0.3]
 [0.2 0.5 0.3]
 [0.4 0.3 0.3]]
Value for exercise is:  0.28


2. If a truck is currently in the suburbs, what is the probability that it will be in the downtown region **the first time** after two time steps? [1.5p]

## 2. [1.5p]

We want the probability that the truck starts in the suburbs, is *not* in downtown after one step, and then enters downtown for the *first time* after two steps.

From the suburbs:

- Probability of going to the suburbs: 0.5  
- Probability of going to the countryside: 0.3  
- Probability of going to downtown: 0.2  

Thus, avoiding downtown in the first step has probability

$$
0.5 + 0.3 = 0.8
$$

Now we consider the valid two-step paths to downtown.

1. Suburbs → Suburbs → Downtown  
2. Suburbs → Countryside → Downtown  

Compute their probabilities:

$$
0.5 \cdot 0.2 = 0.10
$$

$$
0.3 \cdot 0.4 = 0.12
$$

Add them:

$$
0.10 + 0.12 = 0.22
$$

Thus, the probability that the truck is in the downtown region for the *first time* after two time steps is:

$$
0.22
$$


In [82]:
# Part 2

# Fill in the answer to part 2 below as a decimal number
problem1_p2 = 0.22

-----
3. Is this Markov chain irreducible? [1.5p]
-----

A Markov chain is irreducible if you can get from every state to every other state with positive probability. It does not need to happen in one step — only that some path exists.

If the transition matrix has **no zeros at all**, then all transitions are possible in one step. This makes the chain trivially irreducible.

In this case, the matrix has no zeros, so you can go from each state to every other state. Therefore, the Markov chain **is irreducible**.


In [ ]:
# Part 3

# Fill in the answer to part 3 below as a boolean
problem1_irreducible = True

-----
4. What is the stationary distribution? [1.5p]
-----

## 4. [1.5p] Stationary distribution

The transition matrix is

$$
P =
\begin{pmatrix}
0.3 & 0.4 & 0.3 \\
0.2 & 0.5 & 0.3 \\
0.4 & 0.3 & 0.3
\end{pmatrix}
$$

A stationary distribution is a vector $\pi = (\pi_1, \pi_2, \pi_3)$ such that

$$
\pi P = \pi
$$

and

$$
\pi_1 + \pi_2 + \pi_3 = 1.
$$

This yields the following system of equations:

$$
\pi_1 = 0.3\pi_1 + 0.2\pi_2 + 0.4\pi_3
$$

$$
\pi_2 = 0.4\pi_1 + 0.5\pi_2 + 0.3\pi_3
$$

$$
\pi_3 = 0.3\pi_1 + 0.3\pi_2 + 0.3\pi_3
$$

together with the normalization constraint

$$
\pi_1 + \pi_2 + \pi_3 = 1.
$$

Solving the system gives the stationary distribution

$$
\pi = (0.30769231,\; 0.38461538,\; 0.30769231).
$$

Equivalently, in fractional form:

$$
\pi = \left( \frac{4}{13},\; \frac{5}{13},\; \frac{4}{13} \right).
$$


In [4]:
# Part 4
import numpy as np

# Fill in the answer to part 4 below
# the answer should be a numpy array of length 3
# make sure that the entries sums to 1!
problem1_stationary = np.array([26, 37, 27]) * (1/90)
print("Stationary Distribution: ", problem1_stationary)
print("Value: ", (26/90))

#Test 2:
P = np.array([[0.3, 0.4, 0.3], [0.2, 0.5, 0.3], [0.4, 0.3, 0.3]])
n = P.shape[0]

print(P)
print(n)


# Method 1:Method A (linear system): Builds (P^T - I)*n = 0, P^T = Transpose of P, I = Identity matrix, n = stationary matrix
# and enforces ∑π_i = 1 by replacing one row with ones, then solves. 
# =============================================================================
# Method A: Solve a linear system (robust, preferred for small chains)
# We want π such that π = πP and sum(π)=1.
# Rearranged: (P^T - I) π = 0 with the extra constraint 1^T π = 1.
# Replace one row of (P^T - I) with ones and RHS with 1 to make it nonsingular.
# =============================================================================
A = P.T - np.eye(n)
b = np.zeros(n)
A[-1, :] = 1.0          # replace last equation with normalization
b[-1] = 1.0

pi_linear = np.linalg.solve(A, b)
pi_linear = np.maximum(pi_linear, 0)  # clip tiny negatives from round-off
pi_linear = pi_linear / pi_linear.sum()


# Method B (eigenvector): Finds the left eigenvector of P for eigenvalue  1 (i.e., eigenvector of P^⊤), normalizes it.
# =============================================================================
# Method B: Eigenvector of P^T for eigenvalue 1 (quick)
# The stationary distribution is the left eigenvector associated with λ=1.
# =============================================================================
eigvals, eigvecs = np.linalg.eig(P.T)
idx = np.argmin(np.abs(eigvals - 1))
v = np.real(eigvecs[:, idx])
pi_eig = v / v.sum()
pi_eig = np.maximum(pi_eig, 0)        # guard against small negative noise
pi_eig = pi_eig / pi_eig.sum()

print("")


Stationary Distribution:  [0.28888889 0.41111111 0.3       ]
Value:  0.28888888888888886
[[0.3 0.4 0.3]
 [0.2 0.5 0.3]
 [0.4 0.3 0.3]]
3



In [7]:
def stationary_distribution(P):
    """
    Computes the stationary distribution of a Markov chain
    by finding the eigenvector corresponding to eigenvalue 1.
    """
    eigenvalues, eigenvectors = np.linalg.eig(P.T)
    
    # Find the eigenvector associated with eigenvalue 1
    idx = np.argmin(np.abs(eigenvalues - 1))
    vec = np.real(eigenvectors[:, idx])
    
    # Normalize to sum to 1
    stationary = vec / np.sum(vec)
    return stationary

P = np.array([[0.3, 0.4, 0.3], [0.2, 0.5, 0.3], [0.4, 0.3, 0.3]])

print(stationary_distribution(P))

[0.28888889 0.41111111 0.3       ]


-----
5. Advanced question: What is the expected number of steps until the first time one enters the downtown region having started in the suburbs region. Hint: to get within 1 decimal point, it is enough to compute the probabilities for hitting times below 30. [2p]
-----

## 5. [2p] Expected hitting time to downtown

We consider a Markov chain with three regions: downtown (D), suburbs (S), and countryside (C), with transition matrix

$$
P = \begin{pmatrix}
0.3 & 0.4 & 0.3 \\\\
0.2 & 0.5 & 0.3 \\\\
0.4 & 0.3 & 0.3
\end{pmatrix}
$$

We want the expected number of steps until the chain first enters downtown when starting from suburbs. Define the hitting time

$$
T = \min\{n \ge 0 : X_n \text{ is in downtown}\},
$$

and let

$$
h(i) = \mathbb{E}[T \mid X_0 = i].
$$

Clearly,

$$
h_D = 0.
$$

For the non-target states S and C, the first-step recursion gives

$$
h(i) = 1 + \sum_j P_{ij} h(j).
$$

From the suburbs row of \(P\):

$$
h_S = 1 + 0.2 h_D + 0.5 h_S + 0.3 h_C,
$$

and from the countryside row:

$$
h_C = 1 + 0.4 h_D + 0.3 h_S + 0.3 h_C.
$$

Using $( h_D = 0 )$, these become

$$
h_S = 1 + 0.5 h_S + 0.3 h_C,
$$

$$
h_C = 1 + 0.3 h_S + 0.3 h_C.
$$

Rewriting:

$$
0.5 h_S - 0.3 h_C = 1,
$$

$$
-0.3 h_S + 0.7 h_C = 1.
$$

Solving yields

$$
h_C = \frac{40}{13}, \qquad h_S = \frac{50}{13}.
$$

Thus,

$$
\mathbb{E}[T \mid X_0 = S] = \frac{50}{13} \approx 3.8.
$$

In code:

```python
problem1_ET = 50/13


In [85]:
# Part 5

# Fill in the answer to part 5 below
# That is, the expected number of steps as a decimal number
problem1_ET = 3.85

---
## Assignment 2, PROBLEM 2
Maximum Points = 4


Use the **Multi-dimensional Constrained Optimisation** example (in `07-Optimization.ipynb`) to numerically find the MLe for the mean and variance parameter based on `normallySimulatedDataSamples`, an array obtained by a specific simulation of $30$ IID samples from the $Normal(10,2)$ random variable.

Recall that $Normal(\mu, \sigma^2)$ RV has the probability density function given by:

$$
f(x ;\mu, \sigma) = \displaystyle\frac{1}{\sigma\sqrt{2\pi}}\exp\left(\frac{-1}{2\sigma^2}(x-\mu)^2\right)
$$

The two parameters, $\mu \in \mathbb{R} := (-\infty,\infty)$ and $\sigma \in (0,\infty)$, are sometimes referred to as the location and scale parameters.

You know that the log likelihood function for $n$ IID samples from a Normal RV with parameters $\mu$ and $\sigma$ simply follows from $\sum_{i=1}^n \log(f(x_i; \mu,\sigma))$, based on the IID assumption. 

NOTE: When setting bounding boxes for $\mu$ and $\sigma$ try to start with some guesses like $[-20,20]$ and $[0.1,5.0]$ and make it larger if the solution is at the boundary. Making the left bounding-point for $\sigma$ too close to $0.0$ will cause division by zero Warnings. Other numerical instabilities can happen in such iterative numerical solutions to the MLe. You need to be patient and learn by trial-and-error. You will see the mathematical theory in more details in a future course in scientific computing/optimisation. So don't worry too much now except learning to use it for our problems.  

In [ ]:
import numpy as np
from scipy import optimize
# do NOT change the next three lines
np.random.seed(123456) # set seed
# simulate 30 IID samples drawn from Normal(10,2)RV
normallySimulatedDataSamples = np.random.normal(10,2,30) 

# define the negative log likelihoo function you want to minimise by editing XXX
def negLogLklOfIIDNormalSamples(parameters):
    '''return the -log(likelihood) of normallySimulatedDataSamples with mean and var parameters'''
    mu_param=parameters[0]
    sigma_param=parameters[1]
    n = len(normallySimulatedDataSamples) # This is the number of samples
    #log_likelihood = (-1)*n*np.log(1/(sigma_param*np.sqrt(2*np.pi))) * np.exp((-1/(2*sigma_param**2)) * np.sum((normallySimulatedDataSamples - mu_param)**2))
    log_likelihood = np.log((1/(sigma_param*np.sqrt(2*np.pi)))) * n + (-1/(2*sigma_param**2)) * np.sum((normallySimulatedDataSamples - mu_param)**2)
    return -log_likelihood 

# you should only change XXX below and not anything else
parameter_bounding_box=((-20, 20), (0.1, 5.0)) # specify the constraints for each parameter - some guess work...
initial_arguments = np.array([5.0, 1.0]) # point in 2D to initialise the minimize algorithm
result_problem2_opt = optimize.minimize(negLogLklOfIIDNormalSamples, initial_arguments, bounds=parameter_bounding_box, method='L-BFGS-B') 
# call the minimize method above finally! you need to play a bit to get initial conditions and bounding box ok
result_problem2_opt



  message: CONVERGENCE: RELATIVE REDUCTION OF F <= FACTR*EPSMCH
  success: True
   status: 0
      fun: 58.631387282384615
        x: [ 9.269e+00  1.708e+00]
      nit: 14
      jac: [ 1.350e-05 -1.847e-05]
     nfev: 63
     njev: 21
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>

---
## Assignment 2, PROBLEM 3
Maximum Points = 4



Derive the maximum likelihood estimate for $n$ IID samples from a random variable with the following probability density function:
$$
f(x; \lambda) = \frac{1}{24} \lambda^5 x^4 \exp(-\lambda x), \qquad \text{ where, } \lambda>0, x > 0
$$

You can solve the MLe by hand (using pencil paper or using key-strokes). Present your solution as the return value of a function called `def MLeForAssignment2Problem3(x)`, where `x` is a list of $n$ input data points.

In [87]:

# do not change the name of the function, just replace XXX with the appropriate expressions for the MLe
def MLeForAssignment2Problem3(x):
    '''Compute the MLE for λ given n IID samples from'''
    x = np.asarray(x, dtype=float)   # make sure it's a NumPy array
    n = len(x)
    return 5.0 * n / np.sum(x)   # equivalent to 5.0 / np.mean(x)

---
## Assignment 2, PROBLEM 4
Maximum Points = 8


## Random variable generation and transformation

The purpose of this problem is to show that you can implement your own sampler, this will be built in the following three steps:

1. [2p] Implement a Linear Congruential Generator where you tested out a good combination (a large $M$ with $a,b$ satisfying the Hull-Dobell (Thm 6.8)) of parameters. Follow the instructions in the code block.
2. [2p] Using a generator construct random numbers from the uniform $[0,1]$ distribution.
3. [4p] Using a uniform $[0,1]$ random generator, generate samples from 

$$p_0(x) = \frac{\pi}{2}|\sin(2\pi x)|, \quad x \in [0,1] \enspace .$$

Using the **Accept-Reject** sampler (**Algorithm 1** in TFDS notes) with sampling density given by the uniform $[0,1]$ distribution.

-----
1. [2p] Implement a Linear Congruential Generator where you tested out a good combination (a large $M$ with $a,b$ satisfying the Hull-Dobell (Thm 6.8)) of parameters. Follow the instructions in the code block.
-----

### 4.1 [2p] Linear Congruential Generator

We implement a Linear Congruential Generator (LCG) as in the lecture notes (Definition 6.2).

An LCG with parameters $(a, b, M)$ on
$$
\{0, 1, \dots, M-1\}
$$
is defined by
$$
u_{k+1} = (a u_k + b) \bmod M,
$$
where $u_0$ is the seed. This produces a sequence $u_0, u_1, u_2, \dots$ of integers in $\{0,\dots,M-1\}$.

To obtain approximately Uniform$(0,1)$ random numbers we later scale by dividing by $M$. In this problem, however, the generator in part (1) is required to return integers in $\{0,\dots,\text{period}-1\}$, and part (2) performs the scaling.

We choose a large modulus
$$
M = 2^{32},
$$
and the parameters
$$
a = 1664525, \qquad b = 1013904223,
$$
which are the well-known "Numerical Recipes" LCG parameters. They satisfy the Hull–Dobell conditions (Theorem 6.8 in the notes) for full period $M$:

- $\gcd(b, M) = 1$, since $M$ is a power of $2$ and $b$ is odd.
- The only prime divisor of $M$ is $2$, and $2 \mid (a-1)$ since $a$ is odd.
- Because $4 \mid M$, we require $4 \mid (a-1)$; here $a-1 = 1664524$ is divisible by $4$.

Hence the LCG has period $M$.

The implementation is:

```python
def problem4_LCG(size=None, seed=0):
    """
    A linear congruential generator that generates pseudo random numbers according to size.
    
    Parameters
    -------------
    size : an integer denoting how many samples should be produced
    seed : the starting point of the LCG, i.e. u0 in the notes.
    
    Returns
    -------------
    out : a list of the pseudo random integers in {0, 1, ..., M-1}
    """
    M = 2**32
    a = 1664525
    b = 1013904223

    if size is None:
        size = 1

    u = seed
    out = []
    for _ in range(size):
        u = (a * u + b) % M
        out.append(u)
    
    return out


In [16]:

def problem4_LCG(size=None, seed = 0):
    """
    A linear congruential generator that generates pseudo random numbers according to size.
    
    Parameters
    -------------
    size : an integer denoting how many samples should be produced
    seed : the starting point of the LCG, i.e. u0 in the notes.
    
    Returns
    -------------
    out : a list of the pseudo random numbers
    """
    
    """
    Lemma 6.8. Consider a congruential generator D on M= {0,1,...,M−
    1}with period M, then for any starting point u0 ∈M, define ui = D(ui−1)
    then the sequence vi = ui mod K for 1 ≤K ≤M is pseudorandom on
    {0,1,...,K−1}if M is a multiple of K.
    """
    
    # (Numerical Recipes LCG) for choosing the parameters of M, a, b
    M = 2**32
    a = 1664525  
    b = 1013904223
    list_of_random_numbers = []
    u = seed
    for _ in range(size):
        u = (a*u + b) % M
        list_of_random_numbers.append(u)
    
    return list_of_random_numbers

print(problem4_LCG(size=10, seed=0))  # Example usage

[1013904223, 1196435762, 3519870697, 2868466484, 1649599747, 2670642822, 1476291629, 2748932008, 2180890343, 2498801434]


In [17]:

def problem4_uniform(generator, period, size, seed=0):
    """
    Takes a generator and produces samples from the uniform [0,1] distribution according
    to size.
    
    Parameters
    -------------
    generator : a function of type generator(size,seed) and produces the same result as problem1_LCG, i.e. pseudo random numbers in the range {0,1,...,period-1}
    period : the period of the generator
    seed : the seed to be used in the generator provided
    size : an integer denoting how many samples should be produced
    
    Returns
    --------------
    out : a list of the uniform pseudo random numbers
    """
    # Use the provided generator (do NOT shadow the argument)
    raw = generator(size=size, seed=seed)

    # Bring into [0, period-1] even if the plugin returns big/negative ints
    vals = [int(u) % int(period) for u in raw]

    # Map to [0,1). Dividing by float(period) guarantees < 1.
    return [v / float(period) for v in vals]

    #list_of_uniform_random_numbers = [(x / period) for x in generator]    
    
    #return list_of_uniform_random_numbers

print(problem4_uniform(generator=problem4_LCG, period=2**32, size=10, seed=1))



[0.23645552527159452, 0.3692706737201661, 0.5042420323006809, 0.7048832636792213, 0.05054362863302231, 0.3695183543022722, 0.7747629624791443, 0.556188570568338, 0.0164932357147336, 0.6392460397910327]


In [90]:
import math

def problem4_accept_reject(uniformGenerator=None, n_iterations=None, seed=0):
    """
    Accept–Reject sampler to draw samples from
        p0(x) = (pi/2) * |sin(2*pi*x)|  for x in [0,1],
    using q(x) = Uniform(0,1) as the proposal.

    Parameters
    ----------
    uniformGenerator : callable
        A function with signature uniformGenerator(size, seed) that returns
        `size` IID samples in [0,1).
    n_iterations : int
        Number of proposal/acceptance attempts (uses 2 uniforms per iteration).
    seed : int
        Seed forwarded to `uniformGenerator`.

    Returns
    -------
    list[float]
        Accepted samples distributed as p0(x).
    """
    if uniformGenerator is None or n_iterations is None:
        raise ValueError("Provide a uniformGenerator(size, seed) and n_iterations.")

    # Draw 2 uniforms per iteration: one for proposal x, one for acceptance u
    uniforms = uniformGenerator(size=2 * n_iterations, seed=seed)

    accepted = []
    for i in range(0, 2 * n_iterations, 2):
        x = uniforms[i]
        u = uniforms[i + 1]

        # Be robust if the provided generator ever returns values outside [0,1)
        if not (0.0 <= x < 1.0):
            x = x % 1.0
        if not (0.0 <= u < 1.0):
            u = u % 1.0

        # With proposal q(x)=1 on [0,1] and M = max p0(x) = pi/2,
        # acceptance probability is p0(x) / (M*q(x)) = |sin(2*pi*x)|.
        if u <= abs(math.sin(2.0 * math.pi * x)):
            accepted.append(x)

    return accepted


---
#### Local Test for Assignment 2, PROBLEM 4
Evaluate cell below to make sure your answer is valid.                             You **should not** modify anything in the cell below when evaluating it to do a local test of                             your solution.
You may need to include and evaluate code snippets from lecture notebooks in cells above to make the local test work correctly sometimes (see error messages for clues). This is meant to help you become efficient at recalling materials covered in lectures that relate to this problem. Such local tests will generally not be available in the exam.

In [91]:

# If you managed to solve all three parts you can test the following code to see if it runs
# you have to change the period to match your LCG though, this is marked as XXX.
# It is a very good idea to check these things using the histogram function in sagemath
# try with a larger number of samples, up to 10000 should run

print("LCG output: %s" % problem4_LCG(size=10, seed = 1))

period = 2**32

print("Uniform sampler %s" % problem4_uniform(generator=problem4_LCG, period = period, size=10, seed=1))

uniform_sampler = lambda size,seed: problem4_uniform(generator=problem4_LCG, period = period, size=size, seed=seed)

print("Accept-Reject sampler %s" % problem4_accept_reject(uniformGenerator = uniform_sampler,n_iterations=20,seed=1))

LCG output: [1015568748, 1586005467, 2165703038, 3027450565, 217083232, 1587069247, 3327581586, 2388811721, 70837908, 2745540835]
Uniform sampler [0.23645552527159452, 0.3692706737201661, 0.5042420323006809, 0.7048832636792213, 0.05054362863302231, 0.3695183543022722, 0.7747629624791443, 0.556188570568338, 0.0164932357147336, 0.6392460397910327]
Accept-Reject sampler [0.23645552527159452, 0.7747629624791443, 0.2504511415027082, 0.23507591942325234, 0.8608870944008231, 0.6826027217321098, 0.21594200655817986, 0.07054510014131665, 0.12981509510427713, 0.5828870958648622, 0.2629479970782995, 0.9307009153999388, 0.388584918808192]


In [92]:

# If however you did not manage to implement either part 1 or part 2 but still want to check part 3, you can run the code below

def testUniformGenerator(size,seed):
    import random
    random.seed(seed)
    
    return [random.uniform(0,1) for s in range(size)]

print("Accept-Reject sampler %s" % problem4_accept_reject(uniformGenerator=testUniformGenerator, n_iterations=20, seed=1))

Accept-Reject sampler [0.763774618976614, 0.651592972722763, 0.0938595867742349, 0.8357651039198697, 0.762280082457942, 0.22876222127045265, 0.9014274576114836, 0.21659939713061338, 0.23308445025757263, 0.2187810373376886, 0.28978161459048557, 0.8375779756625729, 0.6422943629324456]
