In [ ]:
# Here I will include specific pandas functions and what they do
import pandas as pd

# This is the initial data (CSV file) that we will use for the functions below
data = pd.read_csv("test.csv")

# ---------------------------------------------------------
# pd.read_csv()
# This function is used to retrieve data from a CSV file
# and load it into a pandas DataFrame
data = pd.read_csv("test.csv")

# ---------------------------------------------------------
# data.head()
# This function returns the top n rows of the DataFrame
# By default, it shows the first 5 rows
data.head()

# ---------------------------------------------------------
# data.tail()
# This function returns the bottom n rows of the DataFrame
# By default, it shows the last 5 rows
data.tail()

# ---------------------------------------------------------
# data.sample()
# This function returns a random sample of rows from the DataFrame
# You can specify how many rows you want with n
data.sample(n=5)

# ---------------------------------------------------------
# data.info()
# This function provides a concise summary of the DataFrame
# It includes column names, data types, and non-null counts
data.info()

# ---------------------------------------------------------
# data.dtypes
# This attribute returns the data type of each column in the DataFrame
data.dtypes

# ---------------------------------------------------------
# data.shape
# This attribute returns a tuple representing the dimensions
# of the DataFrame as (number_of_rows, number_of_columns)
data.shape

# ---------------------------------------------------------
# data.size
# This attribute returns the total number of elements
# in the DataFrame (rows × columns)
data.size

# ---------------------------------------------------------
# data.ndim
# This attribute returns the number of dimensions of the object
# 1 for Series, 2 for DataFrame
data.ndim

# ---------------------------------------------------------
# data.describe()
# This function returns descriptive statistics for numerical columns
# such as mean, min, max, standard deviation, quartiles, etc.
data.describe()

# ---------------------------------------------------------
# data["column_name"].unique()
# This function returns all unique values in a specific column
data["column_name"].unique()

# ---------------------------------------------------------
# data["column_name"].nunique()
# This function returns the number of unique values in a specific column
data["column_name"].nunique()

# ---------------------------------------------------------
# data.isnull()
# This function returns a DataFrame of boolean values
# True indicates missing (NaN) values, False otherwise
data.isnull()

# ---------------------------------------------------------
# data.isna()
# This function behaves the same as isnull()
# True indicates missing values, False indicates non-missing values
data.isna()

# ---------------------------------------------------------
# data.fillna()
# This function is used to replace missing values with a specified value
# Example: replace all NaN values with 0
data_filled = data.fillna(0)

# ---------------------------------------------------------
# data.clip()
# This function trims values at specified lower and/or upper thresholds
# Example: limit values in numeric columns between 0 and 100
data_clipped = data.clip(lower=0, upper=100)

# ---------------------------------------------------------
# data.columns
# This attribute returns the column labels of the DataFrame
data.columns

# ---------------------------------------------------------
# data.sort_values()
# This method sorts the DataFrame by the values of a given column
# By default, sorting is done in ascending order
data.sort_values(by="column_name")

# Sort in descending order
data.sort_values(by="column_name", ascending=False)

# ---------------------------------------------------------
# data["column_name"].value_counts()
# This method returns the count of unique values in a column
data["column_name"].value_counts()

# ---------------------------------------------------------
# data.nlargest()
# This method returns the n largest values from a column
data.nlargest(n=5, columns="column_name")

# ---------------------------------------------------------
# data.nsmallest()
# This method returns the n smallest values from a column
data.nsmallest(n=5, columns="column_name")

# ---------------------------------------------------------
# data.copy()
# This method creates a deep copy of the DataFrame
data_copy = data.copy()

# ---------------------------------------------------------
# data.loc[]
# This method is used to access rows and columns by label
# Example: select rows where column value is greater than 50
data.loc[data["column_name"] > 50]

# Example: select specific rows and columns by label
data.loc[0:5, ["column1", "column2"]]

# ---------------------------------------------------------
# data.iloc[]
# This method is used to access rows and columns by integer position
# Example: select first 5 rows
data.iloc[0:5]

# Example: select rows and columns by index position
data.iloc[0:5, 0:2]

# ---------------------------------------------------------
# data.rename()
# This method is used to rename columns or index labels
# Example: rename a column
data_renamed = data.rename(columns={"old_name": "new_name"})

# Example: rename index labels
data_renamed = data.rename(index={0: "first_row"})

# ---------------------------------------------------------
# data.where()
# This method checks the DataFrame for one or more conditions
# and returns values where the condition is True
data.where(data["column_name"] > 50)

# Example: replace values that do not meet the condition with NaN
data.where(data["column_name"] > 50, other=None)

# ---------------------------------------------------------
# data.drop()
# This method is used to drop rows or columns from a DataFrame

# Drop a column
data.drop(columns=["column_name"])

# Drop a row by index
data.drop(index=0)

# ---------------------------------------------------------
# data.groupby()
# This method is used to group data based on a criterion
# Example: group by a column and compute the mean
data.groupby("group_column").mean()

# ---------------------------------------------------------
# data.corr()
# This method computes the correlation between numeric columns
data.corr()

# ---------------------------------------------------------
# data.query()
# This method filters the DataFrame using a query string
data.query("column_name > 50")

# ---------------------------------------------------------
# data.insert()
# This method inserts a new column at a specified position
# Example: insert a column at position 1
data.insert(loc=1, column="new_column", value=0)

# ---------------------------------------------------------
# data.sum()
# This method returns the sum of values over the requested axis

# Column-wise sum (default)
data.sum()

# Row-wise sum
data.sum(axis=1)

# ---------------------------------------------------------
# data.mean()
# This method returns the mean of values over the requested axis

# Column-wise mean (default)
data.mean()

# Row-wise mean
data.mean(axis=1)

# ---------------------------------------------------------
# data.median()
# This method returns the median of values over the requested axis

# Column-wise median (default)
data.median()

# Row-wise median
data.median(axis=1)


# ---------------------------------------------------------
# data.std()
# This method returns the sample standard deviation
# over the requested axis

# Column-wise standard deviation (default)
data.std()

# Row-wise standard deviation
data.std(axis=1)

# ---------------------------------------------------------
# data.apply()
# This method applies a function along rows or columns
# Example: apply a function to each column
data.apply(lambda x: x.max() - x.min())

# Example: apply a function row-wise
data.apply(lambda row: row.sum(), axis=1)

# ---------------------------------------------------------
# pd.merge()
# This method is used to merge two DataFrames
# Example: merge on a common column
merged_df = pd.merge(data, other_df, on="key_column")

# Example: left join
merged_df = pd.merge(data, other_df, on="key_column", how="left")

# ---------------------------------------------------------
# data.astype()
# This method is used to cast a pandas object to a specified data type
# Example: convert a column to integer
data["column_name"] = data["column_name"].astype(int)

# ---------------------------------------------------------
# data.set_index()
# This method sets an existing column as the DataFrame index
data.set_index("column_name")

# ---------------------------------------------------------
# data.reset_index()
# This method resets the index of the DataFrame
# By default, the old index is added as a column
data.reset_index()

# Drop the old index completely
data.reset_index(drop=True)

# ---------------------------------------------------------
# data.at[]
# This method is used to access a single value by label
# Example: get value at a specific row and column
data.at[0, "column_name"]

# ---------------------------------------------------------
# data.iterrows()
# This method iterates over DataFrame rows
# Each iteration returns (index, Series)
for index, row in data.iterrows():
    print(index, row["column_name"])

# ---------------------------------------------------------
# series.iteritems()
# This method iterates over a Series as (index, value) pairs
for index, value in data["column_name"].iteritems():
    print(index, value)


# ---------------------------------------------------------
# pd.to_datetime()
# This method converts string dates into Python datetime objects
data["date_column"] = pd.to_datetime(data["date_column"])

# ---------------------------------------------------------
# pd.to_numeric()
# This method converts an argument to a numeric type
# Invalid parsing will be set to NaN if errors="coerce"
data["numeric_column"] = pd.to_numeric(data["numeric_column"], errors="coerce")

# ---------------------------------------------------------
# data.to_string()
# This method renders the DataFrame as a console-friendly string
print(data.to_string())

# ---------------------------------------------------------
# pd.concat()
# This method concatenates DataFrames along a particular axis
# Example: concatenate rows
combined_df = pd.concat([data, other_df])

# Example: concatenate columns
combined_df = pd.concat([data, other_df], axis=1)

# ---------------------------------------------------------
# data.cov()
# This method computes the pairwise covariance of columns
data.cov()

# ---------------------------------------------------------
# data.duplicated()
# This method returns a boolean Series indicating duplicate rows
data.duplicated()

# ---------------------------------------------------------
# data.drop_duplicates()
# This method removes duplicate rows from the DataFrame
data.drop_duplicates()

# ---------------------------------------------------------
# data.dropna()
# This method drops rows or columns containing missing values

# Drop rows with any NaN values
data.dropna()

# Drop columns with any NaN values
data.dropna(axis=1)

# ---------------------------------------------------------
# data.diff()
# This method computes the first discrete difference
# between values over the requested axis

# Column-wise difference (default)
data.diff()

# Difference between consecutive rows
data.diff(periods=1)

# ---------------------------------------------------------
# data.rank()
# This method assigns ranks to data based on sorting
# By default, ranks are assigned in ascending order
data.rank()

# ---------------------------------------------------------
# data.mask()
# This method replaces values where a condition is True
# with NaN or another specified value
data.mask(data["column_name"] < 0)

# Example: replace values where condition is True with 0
data.mask(data["column_name"] < 0, other=0)

# ---------------------------------------------------------
# data.resample()
# This method is used to resample time-series data
# Requires a DatetimeIndex
# Example: resample by month and compute the mean
data.resample("M").mean()

# ---------------------------------------------------------
# data.transform()
# This method applies a function and returns a DataFrame
# with the same shape as the original
data.transform(lambda x: x - x.mean())

# ---------------------------------------------------------
# data.replace()
# This method is used to replace values in the DataFrame
# Example: replace a specific value
data.replace(-1, 0)

# Example: replace multiple values
data.replace({-1: 0, -2: 1})

# ---------------------------------------------------------
# data.to_csv()
# This method writes the DataFrame to a CSV file
data.to_csv("output.csv", index=False)




In [ ]:
# Here I will include specific pandas functions and what they do
import numpy as np


# --------------------------------------------------
# Example arrays used throughout
# --------------------------------------------------
a = np.array([[1, 2],
              [3, 4]])

b = np.array([3, 4])

# --------------------------------------------------
# np.all()
# --------------------------------------------------
# Checks if ALL elements in the array evaluate to True (non-zero)
# a contains only non-zero values → True
result = np.all(a)
# Returns: True


# --------------------------------------------------
# np.any()
# --------------------------------------------------
# Checks if AT LEAST ONE element evaluates to True (non-zero)
# a has non-zero values → True
result = np.any(a)
# Returns: True


# --------------------------------------------------
# np.take()
# --------------------------------------------------
# Selects elements from an array using indices along an axis
# Here we take rows with index 0 and 1 along axis=0
result = np.take(a, indices=[0, 1], axis=0)
# Returns:
# [[1 2]
#  [3 4]]


# --------------------------------------------------
# np.put()
# --------------------------------------------------
# Replaces elements in array b at specific positions
# b = [3, 4]
# Indices [0, 1] will be replaced with values [10, 20]
np.put(b, [0, 1], [10, 20])
# b is now: [10 20]
# (np.put modifies the array IN-PLACE and returns None)


# --------------------------------------------------
# np.apply_along_axis()
# --------------------------------------------------
# Applies a function to each column (axis=0)
# np.sum is applied column-wise
result = np.apply_along_axis(np.sum, axis=0, arr=a)
# Column sums: [1+3, 2+4]
# Returns: [4 6]


# --------------------------------------------------
# np.apply_over_axes()
# --------------------------------------------------
# Applies a function over specified axes and keeps dimensions
result = np.apply_over_axes(np.sum, a, axes=[0])
# Returns:
# [[4 6]]


# --------------------------------------------------
# np.diag()
# --------------------------------------------------
# Extracts the diagonal of a matrix
result = np.diag(a)
# Returns: [1 4]


# --------------------------------------------------
# np.diagflat()
# --------------------------------------------------
# Creates a 2D array with input values on the diagonal
result = np.diagflat([1, 2, 3])
# Returns:
# [[1 0 0]
#  [0 2 0]
#  [0 0 3]]


# --------------------------------------------------
# np.diag_indices()
# --------------------------------------------------
# Returns indices of diagonal elements for a square matrix
idx = np.diag_indices(2)
# Returns: (array([0, 1]), array([0, 1]))
# Can be used like: a[idx]


# --------------------------------------------------
# np.asmatrix()
# --------------------------------------------------
# Converts input to a NumPy matrix object (2D only)
result = np.asmatrix(a)
# Returns: matrix([[1, 2], [3, 4]])


# --------------------------------------------------
# np.bmat()
# --------------------------------------------------
# Builds a block matrix using string notation
result = np.bmat("a")
# Returns the same matrix as a, but as a matrix object


# --------------------------------------------------
# np.eye()
# --------------------------------------------------
# Creates an identity matrix
result = np.eye(3)
# Returns:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


# --------------------------------------------------
# np.hypot()
# --------------------------------------------------
# Computes sqrt(x^2 + y^2)
result = np.hypot(3, 4)
# Returns: 5.0


# --------------------------------------------------
# np.absolute()
# --------------------------------------------------
# Computes absolute value element-wise
result = np.absolute([-1, -2, 3])
# Returns: [1 2 3]


# --------------------------------------------------
# np.ceil()
# --------------------------------------------------
# Rounds values UP to nearest integer
result = np.ceil([1.2, 2.5, 3.1])
# Returns: [2. 3. 4.]


# --------------------------------------------------
# np.floor()
# --------------------------------------------------
# Rounds values DOWN to nearest integer
result = np.floor([1.2, 2.5, 3.9])
# Returns: [1. 2. 3.]


# --------------------------------------------------
# np.degrees()
# --------------------------------------------------
# Converts radians to degrees
result = np.degrees(np.pi)
# Returns: 180.0


# --------------------------------------------------
# np.radians()
# --------------------------------------------------
# Converts degrees to radians
result = np.radians(180)
# Returns: 3.141592653589793


# --------------------------------------------------
# np.ones_like()
# --------------------------------------------------
# Creates an array of ones with the same shape as 'a'
result = np.ones_like(a)
# Returns:
# [[1 1]
#  [1 1]]


# --------------------------------------------------
# np.full_like()
# --------------------------------------------------
# Creates an array filled with a specific value, same shape as 'a'
result = np.full_like(a, fill_value=7)
# Returns:
# [[7 7]
#  [7 7]]


# --------------------------------------------------
# np.sin()
# --------------------------------------------------
# Computes sine (input in radians)
result = np.sin(np.pi / 2)
# Returns: 1.0


# --------------------------------------------------
# np.cos()
# --------------------------------------------------
# Computes cosine (input in radians)
result = np.cos(0)
# Returns: 1.0


# --------------------------------------------------
# np.tan()
# --------------------------------------------------
# Computes tangent (input in radians)
result = np.tan(np.pi / 4)
# Returns: 1.0


# --------------------------------------------------
# np.sinh()
# --------------------------------------------------
# Computes hyperbolic sine
result = np.sinh(1)
# Returns: approximately 1.175201





#--------------------------------------------------
#   NEXT SECTION
# --------------------------------------------------






# --------------------------------------------------
# Example arrays used throughout
# --------------------------------------------------
x = np.array([3, 1, 4, 1, 5])
y = np.array([1, np.nan, 3])
m = np.array([[1, 2],
              [3, 4]])

# --------------------------------------------------
# np.argmin()
# --------------------------------------------------
# Returns the index of the smallest value
result = np.argmin(x)
# x = [3, 1, 4, 1, 5]
# First minimum value (1) is at index 1
# Returns: 1


# --------------------------------------------------
# np.argmax()
# --------------------------------------------------
# Returns the index of the largest value
result = np.argmax(x)
# Max value (5) is at index 4
# Returns: 4


# --------------------------------------------------
# np.nanargmin()
# --------------------------------------------------
# Same as argmin, but ignores NaN values
result = np.nanargmin(y)
# y = [1, NaN, 3]
# Minimum non-NaN value is 1 at index 0
# Returns: 0


# --------------------------------------------------
# np.nanargmax()
# --------------------------------------------------
# Same as argmax, but ignores NaN values
result = np.nanargmax(y)
# Max non-NaN value is 3 at index 2
# Returns: 2


# --------------------------------------------------
# np.amax()
# --------------------------------------------------
# Returns the maximum value in the array
result = np.amax(x)
# Returns: 5


# --------------------------------------------------
# np.amin()
# --------------------------------------------------
# Returns the minimum value in the array
result = np.amin(x)
# Returns: 1


# --------------------------------------------------
# np.insert()
# --------------------------------------------------
# Inserts values into an array at a given index
# Insert 99 at index 2
result = np.insert(x, 2, 99)
# Original x unchanged
# Returns: [ 3  1 99  4  1  5 ]


# --------------------------------------------------
# np.roll()
# --------------------------------------------------
# Shifts elements cyclically
result = np.roll(x, 2)
# Shifts right by 2
# Returns: [1 5 3 1 4]


# --------------------------------------------------
# np.identity()
# --------------------------------------------------
# Creates an identity matrix
result = np.identity(3)
# Returns:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


# --------------------------------------------------
# np.arange()
# --------------------------------------------------
# Creates evenly spaced values (like range)
result = np.arange(0, 10, 2)
# Returns: [0 2 4 6 8]


# --------------------------------------------------
# np.place()
# --------------------------------------------------
# Replaces elements where condition is True (IN-PLACE)
z = np.array([1, 2, 3, 4])
np.place(z, z > 2, 99)
# Values greater than 2 replaced
# z is now: [ 1  2 99 99 ]


# --------------------------------------------------
# np.extract()
# --------------------------------------------------
# Extracts elements that satisfy a condition
result = np.extract(x > 2, x)
# Returns: [3 4 5]


# --------------------------------------------------
# np.compress()
# --------------------------------------------------
# Selects elements using a boolean mask
mask = [True, False, True, False, True]
result = np.compress(mask, x)
# Returns: [3 4 5]


# --------------------------------------------------
# np.rot90()
# --------------------------------------------------
# Rotates array 90 degrees counterclockwise
result = np.rot90(m)
# Returns:
# [[2 4]
#  [1 3]]


# --------------------------------------------------
# np.npv()
# --------------------------------------------------
# Computes Net Present Value
rate = 0.1
cashflows = [-100, 30, 40, 50]
result = np.npv(rate, cashflows)
# Returns: approx 2.1


# --------------------------------------------------
# np.fv()
# --------------------------------------------------
# Computes Future Value of an investment
result = np.fv(0.05, 10, -100, -1000)
# Returns: future value after 10 periods


# --------------------------------------------------
# np.pv()
# --------------------------------------------------
# Computes Present Value of an investment
result = np.pv(0.05, 10, -100, 0)
# Returns: present value


# --------------------------------------------------
# np.power()
# --------------------------------------------------
# Raises elements to a power
result = np.power([1, 2, 3], 2)
# Returns: [1 4 9]


# --------------------------------------------------
# np.float_power()
# --------------------------------------------------
# Like power, but always returns floats
result = np.float_power([1, 2, 3], 2)
# Returns: [1. 4. 9.]


# --------------------------------------------------
# np.log()
# --------------------------------------------------
# Natural logarithm (base e)
result = np.log(np.e)
# Returns: 1.0


# --------------------------------------------------
# np.log1p()
# --------------------------------------------------
# Computes log(1 + x) accurately for small x
result = np.log1p(0.001)
# Returns: approx 0.0009995


# --------------------------------------------------
# np.cosh()
# --------------------------------------------------
# Hyperbolic cosine
result = np.cosh(1)
# Returns: approx 1.54308


# --------------------------------------------------
# np.tanh()
# --------------------------------------------------
# Hyperbolic tangent
result = np.tanh(1)
# Returns: approx 0.76159


# --------------------------------------------------
# np.arcsin()
# --------------------------------------------------
# Inverse sine (returns radians)
result = np.arcsin(1)
# Returns: π/2 ≈ 1.5708


# --------------------------------------------------
# np.arccos()
# --------------------------------------------------
# Inverse cosine (returns radians)
result = np.arccos(1)
# Returns: 0.0


# --------------------------------------------------
# np.exp()
# --------------------------------------------------
# Computes e^x
result = np.exp(1)
# Returns: approx 2.71828


# --------------------------------------------------
# np.exp2()
# --------------------------------------------------
# Computes 2^x
result = np.exp2(3)
# Returns: 8.0


# --------------------------------------------------
# np.fix()
# --------------------------------------------------
# Rounds toward zero
result = np.fix([-2.9, -2.1, 2.9])
# Returns: [-2. -2.  2.]







#--------------------------------------------------
#   NEXT SECTION
# --------------------------------------------------






# --------------------------------------------------
# Example arrays used throughout
# --------------------------------------------------
a = np.array([1, 2, 3, 4])
b = np.array([True, False, True, False])
M = np.array([[1, 2],
              [3, 4]])
x = np.array([1.2, 2.5, 3.7])

# --------------------------------------------------
# np.delete()
# --------------------------------------------------
# Deletes elements at specified indices (returns NEW array)
result = np.delete(a, 1)
# Removes element at index 1
# Returns: [1 3 4]


# --------------------------------------------------
# np.append()
# --------------------------------------------------
# Appends values to the end of an array (returns NEW array)
result = np.append(a, [5, 6])
# Returns: [1 2 3 4 5 6]


# --------------------------------------------------
# np.around()
# --------------------------------------------------
# Rounds values to a given number of decimals
result = np.around(x, decimals=0)
# Returns: [1. 2. 4.]


# --------------------------------------------------
# np.flip()
# --------------------------------------------------
# Reverses elements along all axes
result = np.flip(a)
# Returns: [4 3 2 1]


# --------------------------------------------------
# np.fliplr()
# --------------------------------------------------
# Flips a 2D array left–right (columns)
result = np.fliplr(M)
# Returns:
# [[2 1]
#  [4 3]]


# --------------------------------------------------
# np.flipud()
# --------------------------------------------------
# Flips a 2D array up–down (rows)
result = np.flipud(M)
# Returns:
# [[3 4]
#  [1 2]]


# --------------------------------------------------
# np.triu()
# --------------------------------------------------
# Returns the upper triangular part of a matrix
result = np.triu(M)
# Returns:
# [[1 2]
#  [0 4]]


# --------------------------------------------------
# np.tril()
# --------------------------------------------------
# Returns the lower triangular part of a matrix
result = np.tril(M)
# Returns:
# [[1 0]
#  [3 4]]


# --------------------------------------------------
# np.tile()
# --------------------------------------------------
# Repeats an array multiple times
result = np.tile([1, 2], 3)
# Returns: [1 2 1 2 1 2]


# --------------------------------------------------
# np.reshape()
# --------------------------------------------------
# Changes shape WITHOUT changing data
result = np.reshape(a, (2, 2))
# Returns:
# [[1 2]
#  [3 4]]


# --------------------------------------------------
# np.ravel()
# --------------------------------------------------
# Flattens array into 1D (view if possible)
result = np.ravel(M)
# Returns: [1 2 3 4]


# --------------------------------------------------
# np.isinf()
# --------------------------------------------------
# Checks for positive or negative infinity
result = np.isinf([1, np.inf, -np.inf])
# Returns: [False True True]


# --------------------------------------------------
# np.isrealobj()
# --------------------------------------------------
# Checks if object contains only real numbers
result = np.isrealobj([1, 2.5])
# Returns: True


# --------------------------------------------------
# np.isscalar()
# --------------------------------------------------
# Checks if input is a scalar value
result = np.isscalar(10)
# Returns: True


# --------------------------------------------------
# np.isneginf()
# --------------------------------------------------
# Checks for negative infinity
result = np.isneginf([-np.inf, 0, np.inf])
# Returns: [ True False False ]


# --------------------------------------------------
# np.isposinf()
# --------------------------------------------------
# Checks for positive infinity
result = np.isposinf([-np.inf, 0, np.inf])
# Returns: [False False  True]


# --------------------------------------------------
# np.log2()
# --------------------------------------------------
# Base-2 logarithm
result = np.log2(8)
# Returns: 3.0


# --------------------------------------------------
# np.log10()
# --------------------------------------------------
# Base-10 logarithm
result = np.log10(100)
# Returns: 2.0


# --------------------------------------------------
# np.dot()
# --------------------------------------------------
# Dot product / matrix multiplication
result = np.dot(M, M)
# Returns:
# [[ 7 10]
#  [15 22]]


# --------------------------------------------------
# np.vdot()
# --------------------------------------------------
# Dot product with complex conjugate
result = np.vdot([1, 2], [3, 4])
# Returns: 11


# --------------------------------------------------
# np.trunc()
# --------------------------------------------------
# Truncates decimal part (toward zero)
result = np.trunc([-2.9, 2.9])
# Returns: [-2.  2.]


# --------------------------------------------------
# np.divide()
# --------------------------------------------------
# Element-wise division
result = np.divide([10, 20], [2, 4])
# Returns: [5. 5.]


# --------------------------------------------------
# np.floor_divide()
# --------------------------------------------------
# Division rounded DOWN to nearest integer
result = np.floor_divide([7, 9], [2, 2])
# Returns: [3 4]


# --------------------------------------------------
# np.true_divide()
# --------------------------------------------------
# True division (always returns float)
result = np.true_divide([7, 9], [2, 2])
# Returns: [3.5 4.5]


# --------------------------------------------------
# np.logical_or()
# --------------------------------------------------
# Element-wise logical OR
result = np.logical_or(b, [False, False, True, True])
# Returns: [ True False  True  True ]


# --------------------------------------------------
# np.logical_and()
# --------------------------------------------------
# Element-wise logical AND
result = np.logical_and(b, [True, True, False, False])
# Returns: [ True False False False ]


# --------------------------------------------------
# np.logical_not()
# --------------------------------------------------
# Element-wise logical NOT
result = np.logical_not(b)
# Returns: [False  True False  True]


# --------------------------------------------------
# np.logical_xor()
# --------------------------------------------------
# Element-wise logical XOR
result = np.logical_xor(b, [True, True, False, False])
# Returns: [False True True False]


# --------------------------------------------------
# np.array_equal()
# --------------------------------------------------
# Checks if two arrays have same shape and elements
result = np.array_equal([1, 2], [1, 2])
# Returns: True


# --------------------------------------------------
# np.array_equiv()
# --------------------------------------------------
# Like array_equal, but allows broadcasting
result = np.array_equiv([1, 2], [[1, 2], [1, 2]])
# Returns: True


# --------------------------------------------------
# np.arctan2()
# --------------------------------------------------
# Computes angle from x-axis given y and x
result = np.arctan2(1, 1)
# Returns: π/4 ≈ 0.785398


# --------------------------------------------------
# np.equal()
# --------------------------------------------------
# Element-wise equality comparison
result = np.equal([1, 2, 3], [1, 0, 3])
# Returns: [ True False  True ]








#--------------------------------------------------
#   NEXT SECTION
# --------------------------------------------------






import numpy as np

# --------------------------------------------------
# Example data used throughout
# --------------------------------------------------
a = np.array([[1, 2], [3, 4]])
x = np.array([1, 2, 3])
y = np.array([1.0, np.nan, np.inf, -np.inf])
c = np.array([1+2j, 3+0j])
b = np.array([1, 2, 2, 3, 3, 3])

# --------------------------------------------------
# np.tri()
# --------------------------------------------------
# Creates a lower triangular matrix of ones
result = np.tri(3)
# Returns:
# [[1. 0. 0.]
#  [1. 1. 0.]
#  [1. 1. 1.]]


# --------------------------------------------------
# np.empty()
# --------------------------------------------------
# Creates an array WITHOUT initializing values
result = np.empty((2, 2))
# Returns: arbitrary (garbage) values


# --------------------------------------------------
# np.empty_like()
# --------------------------------------------------
# Same shape as given array, uninitialized values
result = np.empty_like(a)
# Returns: arbitrary values with shape (2, 2)


# --------------------------------------------------
# np.zeros()
# --------------------------------------------------
# Creates array filled with zeros
result = np.zeros((2, 3))
# Returns:
# [[0. 0. 0.]
#  [0. 0. 0.]]


# --------------------------------------------------
# np.zeros_like()
# --------------------------------------------------
# Same shape as a, filled with zeros
result = np.zeros_like(a)
# Returns:
# [[0 0]
#  [0 0]]


# --------------------------------------------------
# np.ones()
# --------------------------------------------------
# Creates array filled with ones
result = np.ones((2, 2))
# Returns:
# [[1. 1.]
#  [1. 1.]]


# --------------------------------------------------
# np.iscomplex()
# --------------------------------------------------
# Checks element-wise if values are complex
result = np.iscomplex(c)
# Returns: [ True False ]


# --------------------------------------------------
# np.isnan()
# --------------------------------------------------
# Checks for NaN values
result = np.isnan(y)
# Returns: [False  True False False]


# --------------------------------------------------
# np.iscomplexobj()
# --------------------------------------------------
# Checks if array contains any complex numbers
result = np.iscomplexobj(c)
# Returns: True


# --------------------------------------------------
# np.isreal()
# --------------------------------------------------
# Checks element-wise if values are real
result = np.isreal(c)
# Returns: [False  True]


# --------------------------------------------------
# np.isfinite()
# --------------------------------------------------
# True for finite numbers (not inf or NaN)
result = np.isfinite(y)
# Returns: [ True False False False ]


# --------------------------------------------------
# np.isfortran()
# --------------------------------------------------
# Checks if array is stored in column-major order
result = np.isfortran(a)
# Returns: False


# --------------------------------------------------
# np.random.rand()
# --------------------------------------------------
# Generates random numbers in [0, 1)
result = np.random.rand(3)
# Returns: e.g. [0.23 0.81 0.45]


# --------------------------------------------------
# np.random.randn()
# --------------------------------------------------
# Random numbers from standard normal distribution
result = np.random.randn(3)
# Returns: e.g. [-0.12 1.34 0.56]


# --------------------------------------------------
# ndarray.flat
# --------------------------------------------------
# Returns a 1D iterator over array elements
result = list(a.flat)
# Returns: [1, 2, 3, 4]


# --------------------------------------------------
# np.expm1()
# --------------------------------------------------
# Computes exp(x) - 1 accurately for small x
result = np.expm1(0.001)
# Returns: approx 0.0010005


# --------------------------------------------------
# np.bincount()
# --------------------------------------------------
# Counts occurrences of non-negative integers
result = np.bincount(b)
# b = [1, 2, 2, 3, 3, 3]
# Returns: [0 1 2 3]


# --------------------------------------------------
# np.rint()
# --------------------------------------------------
# Rounds to nearest integer
result = np.rint([1.2, 1.5, 2.7])
# Returns: [1. 2. 3.]


# --------------------------------------------------
# np.arctan()
# --------------------------------------------------
# Inverse tangent (returns radians)
result = np.arctan(1)
# Returns: π/4 ≈ 0.785398


# --------------------------------------------------
# np.cbrt()
# --------------------------------------------------
# Computes cube root
result = np.cbrt(27)
# Returns: 3.0


# --------------------------------------------------
# np.not_equal()
# --------------------------------------------------
# Element-wise inequality
result = np.not_equal([1, 2, 3], [1, 0, 3])
# Returns: [False  True False]


# --------------------------------------------------
# np.less()
# --------------------------------------------------
# Element-wise less-than comparison
result = np.less([1, 2, 3], [2, 2, 2])
# Returns: [ True False False ]


# --------------------------------------------------
# np.less_equal()
# --------------------------------------------------
# Element-wise ≤ comparison
result = np.less_equal([1, 2, 3], [2, 2, 2])
# Returns: [ True  True False ]


# --------------------------------------------------
# np.greater()
# --------------------------------------------------
# Element-wise greater-than comparison
result = np.greater([1, 2, 3], [2, 2, 2])
# Returns: [False False  True]


# --------------------------------------------------
# np.greater_equal()
# --------------------------------------------------
# Element-wise ≥ comparison
result = np.greater_equal([1, 2, 3], [2, 2, 2])
# Returns: [False  True  True]


# --------------------------------------------------
# np.prod()
# --------------------------------------------------
# Computes product of all elements
result = np.prod([1, 2, 3, 4])
# Returns: 24


# --------------------------------------------------
# np.square()
# --------------------------------------------------
# Squares each element
result = np.square([1, 2, 3])
# Returns: [1 4 9]



